#!/usr/bin/env bash

set -eo pipefail

# Redirect output to stderr.
exec 1>&2

which 'ktfmt' >/dev/null || { echo "ktfmt not found. Install it first."; exit 1; }


files_to_format="$(git diff --name-only --cached --relative -- '*.kt' '*.kts')"
if [[ -z "$files_to_format" ]]; then
  exit 0
fi

if [[ -z "$files_to_format" ]]; then
  exit 0
fi

echo "Formatting kotlin files..."

git stash save -ku

on_exit() {
  git stash pop || echo "if changes were stashed, you should manually re-apply them"
  exit 0
}
trap 'on_exit' EXIT

make format-staged

# Stage the formatted files so they can be committed
while IFS= read -r file; do
  if [[ -f "$file" ]]; then
    git add "$file"
  fi
done <<< "$files_to_format"
