services:
  eventstore.db:
    image: eventstore/eventstore:24.6.0-alpha-arm64v8
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "2113:2113"

  postgres:
    image: postgres:17-alpine
    command: "postgres -N 200"
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - "./skull-king-init.sql:/docker-entrypoint-initdb.d/skull-king-init.sql"

#  lgtm:
#    image: docker.io/grafana/otel-lgtm:0.8.3
#    ports:
#      - "3000:3000"
#      - "4317:4317"
#      - "4318:4318"
#    environment:
#      OTEL_METRIC_EXPORT_INTERVAL: "5000"
