/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.10/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "skull-king"
include(
    ":adapters:esdb",
    ":adapters:in-memory",
    ":adapters:web:api",
    ":adapters:web:client",
    ":adapters:web:server",
    ":application:input-ports",
    ":application:output-ports",
    ":application:services",
    ":domain:auth",
    ":domain:game",
    ":lib:forkhandles-extensions",
)
